SECTIONS = {310: ["gitglossary.adoc"],
            300: ["git-init.adoc",
                  "git-clone.adoc",
                  "git-add.adoc"],
            280: ["git-status.adoc",
                  "git-diff.adoc",
                  "git-commit.adoc",
                  "git-notes.adoc",
                  "git-restore.adoc",
                  "git-reset.adoc",
                  "git-rm.adoc",
                  "git-mv.adoc"],
            260: ["git-branch.adoc",
                  "git-log.adoc",
                  "git-shortlog.adoc",
                  "git-describe.adoc"],
            240: ["git-show.adoc",
                  "git-checkout.adoc",
                  "git-merge.adoc",
                  "git-mergetool.adoc",
                  "git-stash.adoc",
                  "git-tag.adoc",
                  "git-worktree.adoc"],
            220: ["git-fetch.adoc",
                  "git-pull.adoc",
                  "git-push.adoc",
                  "git-remote.adoc",
                  "git-submodule.adoc",
                  "git-rebase.adoc"],
            90: ["git-cvsexportcommit.adoc",
                 "git-cvsimport.adoc",
                 "git-cvsserver.adoc",
                 "git-unpack-file.adoc",
                 "git-unpack-objects.adoc",
                 "git-fast-export.adoc",
                 "git-fast-import.adoc",
                 "git-fetch-pack.adoc",
                 "git-filter-branch.adoc",
                 "git-update-server-info.adoc",
                 "git-sh-i18n.adoc",
                 "git-sh-i18n--envsubst.adoc",
                 "git-send-pack.adoc",
                 "git-remote-ext.adoc",
                 "git-remote-fd.adoc",
                 "git-receive-pack.adoc",
                 "git-send-pack.adoc",
                 "git-p4.adoc",
                 "git-symbolic-ref.adoc",
                 "git-merge-base.adoc",
                 "git-merge-file.adoc",
                 "git-merge-index.adoc",
                 "git-credential-cache--daemon.adoc",
                 "git-credential-cache.adoc",
                 "git-quiltimport.adoc",
                 ],
            80: ["git-cat-file.adoc",
                 "git-check-ignore.adoc",
                 "git-checkout-index.adoc",
                 "git-commit-tree.adoc",
                 "git-count-objects.adoc",
                 "git-diff-index.adoc",
                 "git-diff-tree.adoc",
                 "git-for-each-ref.adoc",
                 "git-hash-object.adoc",
                 "git-ls-files.adoc",
                 "git-ls-tree.adoc",
                 "git-merge-base.adoc",
                 "git-pack-objects.adoc",
                 "git-pack-redundant.adoc",
                 "git-pack-refs.adoc",
                 "git-patch-id.adoc",
                 "git-read-tree.adoc",
                 "git-rev-list.adoc",
                 "git-rev-parse.adoc",
                 "git-show-ref.adoc",
                 "git-symbolic-ref.adoc",
                 "git-update-index.adoc",
                 "git-update-ref.adoc",
                 "git-verify-pack.adoc",
                 "git-write-tree.adoc"
                 ]
            }
