#!/usr/bin/python
import os
import shutil

## get the relative path of the files from the env var SOURCE_PATH
relative_path = os.getenv('SOURCE_PATH')
if relative_path is None:
    relative_path = '..'

with open('sources.txt') as f:
    sources = f.read().splitlines()
    for source in sources:
        try:
            shutil.copy2(os.path.join(relative_path, source), os.path.join("en", source))
        except FileNotFoundError:
            print(f"File not found: {source}")
        except shutil.SameFileError:
            print(f"File is the same: {source}")

shutil.copy2(os.path.join(relative_path, "..", "GIT-VERSION-FILE"), ".")
